# Site settings
name: Mikael Johan Rosenhed
description: Game Designer Generalist
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
url: "https://Mikael925.github.io"
baseurl: ""

# Navigation links
navigation:
  - title: About Me
    url: /
  - title: Narrative Design
    url: /narrative-design/
  - title: Level Design
    url: /level-design/
  - title: Sound Design
    url: /sound-design/
  - title: Systems Design
    url: /systems-design/
  - title: Generalist
    url: /generalist/

# Footer links
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

# Build settings
permalink: /:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
